import type { LucideIcon, LucideProps } from 'lucide-react'
import {
  AlertTriangle,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignStartVertical,
  Armchair,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BellRing,
  BringToFront,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  ClipboardList,
  Clock,
  CookingPot,
  Copy,
  DoorClosed,
  DoorOpen,
  Eye,
  EyeOff,
  Flower2,
  Footprints,
  Grid2x2,
  Grid3x3,
  GripVertical,
  Hand,
  History,
  Hourglass,
  Info,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  ListOrdered,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Menu,
  Merge,
  Minus,
  Moon,
  MousePointer2,
  PartyPopper,
  Pencil,
  PersonStanding,
  Phone,
  PieChart,
  Plus,
  Redo2,
  RefreshCw,
  Save,
  Scan,
  Search,
  SendToBack,
  Settings,
  Shapes,
  Sparkles,
  SquareMousePointer,
  Star,
  Store,
  StretchHorizontal,
  StretchVertical,
  Sun,
  Table2,
  Theater,
  Timer,
  Trash2,
  Trees,
  TrendingUp,
  Undo2,
  User,
  UserCheck,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wine,
  X,
  XCircle,
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface MaterialIconProps {
  name: string
  filled?: boolean
  className?: string
  size?: number
}

/** Maps Material Symbols ligature names used in the app to Lucide icons. */
const ICON_MAP: Record<string, LucideIcon> = {
  add: Plus,
  align_horizontal_center: AlignCenterVertical,
  align_horizontal_left: AlignStartVertical,
  align_horizontal_right: AlignEndVertical,
  align_vertical_bottom: AlignEndHorizontal,
  align_vertical_center: AlignCenterHorizontal,
  align_vertical_top: AlignStartHorizontal,
  analytics: BarChart3,
  bar_chart: BarChart3,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  cake: Cake,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  cancel: XCircle,
  category: Shapes,
  celebration: PartyPopper,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  crop_free: Scan,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  delete: Trash2,
  desk: SquareMousePointer,
  directions_walk: Footprints,
  door_front: DoorClosed,
  drag_indicator: GripVertical,
  edit: Pencil,
  error: AlertTriangle,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  event_seat: Armchair,
  exit_to_app: DoorOpen,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  fit_screen: Maximize2,
  flip_to_back: SendToBack,
  flip_to_front: BringToFront,
  format_list_numbered: ListOrdered,
  grid_on: Grid3x3,
  grid_view: Grid2x2,
  group: Users,
  history: History,
  horizontal_distribute: StretchHorizontal,
  hourglass_empty: Hourglass,
  how_to_reg: UserCheck,
  info: Info,
  language: Languages,
  layers: Layers,
  light_mode: Sun,
  local_bar: Wine,
  local_florist: Flower2,
  location_on: MapPin,
  lock: Lock,
  lock_open: LockOpen,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  map: Map,
  menu: Menu,
  merge: Merge,
  near_me: MousePointer2,
  notifications: Bell,
  notifications_active: BellRing,
  pan_tool: Hand,
  pending_actions: ClipboardList,
  person: User,
  person_add: UserPlus,
  pie_chart: PieChart,
  queue: ListOrdered,
  redo: Redo2,
  remove: Minus,
  restaurant: UtensilsCrossed,
  save: Save,
  schedule: Clock,
  search: Search,
  select_all: SquareMousePointer,
  settings: Settings,
  skillet: CookingPot,
  star: Star,
  store: Store,
  storefront: Store,
  sync: RefreshCw,
  table_restaurant: Table2,
  theater_comedy: Theater,
  timer: Timer,
  touch_app: Hand,
  trending_up: TrendingUp,
  undo: Undo2,
  vertical_distribute: StretchVertical,
  view_quilt: LayoutGrid,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: AlertTriangle,
  wc: PersonStanding,
  yard: Trees,
}

export function MaterialIcon({ name, filled, className, size = 20 }: MaterialIconProps) {
  const Icon = ICON_MAP[name] ?? CircleHelp
  const props: LucideProps = {
    size,
    className: cn('shrink-0', className),
    strokeWidth: filled ? 2.5 : 2,
    'aria-hidden': true,
  }
  return <Icon {...props} />
}

export const iconProps = { size: 20 } as const
export const iconPropsSm = { size: 16 } as const
export const iconPropsLg = { size: 24 } as const
export const iconPropsHero = { size: 32 } as const
